// resultat gagne 1 perdre 0
export default {
  nomComplet: "Tanjona",
  jeton: "1.980",
  mesParis: [
    {
      resultat: 0,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "ManchesterLOLOL llll",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester Yes of",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 1,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 1,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 0,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 0,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 1,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 0,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
    {
      resultat: 1,
      competition: "Ligue des Champions",
      competCut: "Ligue des Champ...",
      date: "01/01/2021",
      heure: "12:12",
      jeton: 500,
      pari: "X1",
      equipe1: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
      equipe2: {
        nom: "Manchester",
        iconLink: require("../../../assets/adaptive-icon.png"),
        score: 1,
      },
    },
  ],
};
